// <auto-generated />
using Acme.DemoServer.Processing.DataAccess.PostgreSql.EfModels;
using Acme.DemoServer.Processing.DataAccess.PostgreSql.EfModelsOptimized;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ProcessingDbContext), typeof(ProcessingDbContextModel))]
