// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using ShtrihM.DemoServer.Processing.DataAccess.PostgreSql.EfModels;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ShtrihM.DemoServer.Processing.DataAccess.PostgreSql.EfModelsOptimized
{
    [DbContext(typeof(ProcessingDbContext))]
    public partial class ProcessingDbContextModel : RuntimeModel
    {
        static ProcessingDbContextModel()
        {
            var model = new ProcessingDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static ProcessingDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
