// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Acme.DemoServer.Processing.DataAccess.PostgreSql.EfModelsOptimized
{
    public partial class ProcessingDbContextModel
    {
        private ProcessingDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("8387ee5c-a25a-480e-972f-59c00613d504"), entityTypeCount: 7)
        {
        }

        partial void Initialize()
        {
            var demoobjectx = DemoobjectxEntityType.Create(this);
            var pdChangeTracker = PdChangeTrackerEntityType.Create(this);
            var pdDemoDelayTask = PdDemoDelayTaskEntityType.Create(this);
            var pdDemoObject = PdDemoObjectEntityType.Create(this);
            var pdSystemLog = PdSystemLogEntityType.Create(this);
            var pdTablePartition = PdTablePartitionEntityType.Create(this);
            var systemsetting = SystemsettingEntityType.Create(this);

            DemoobjectxEntityType.CreateAnnotations(demoobjectx);
            PdChangeTrackerEntityType.CreateAnnotations(pdChangeTracker);
            PdDemoDelayTaskEntityType.CreateAnnotations(pdDemoDelayTask);
            PdDemoObjectEntityType.CreateAnnotations(pdDemoObject);
            PdSystemLogEntityType.CreateAnnotations(pdSystemLog);
            PdTablePartitionEntityType.CreateAnnotations(pdTablePartition);
            SystemsettingEntityType.CreateAnnotations(systemsetting);

            var sequences = new Dictionary<(string, string), ISequence>();
            var sequence_changetracker = new RuntimeSequence(
                "sequence_changetracker",
                this,
                typeof(long));

            sequences[("sequence_changetracker", null)] = sequence_changetracker;

            var sequence_demodelaytask = new RuntimeSequence(
                "sequence_demodelaytask",
                this,
                typeof(long));

            sequences[("sequence_demodelaytask", null)] = sequence_demodelaytask;

            var sequence_demoobject = new RuntimeSequence(
                "sequence_demoobject",
                this,
                typeof(long));

            sequences[("sequence_demoobject", null)] = sequence_demoobject;

            var sequence_demoobjectx = new RuntimeSequence(
                "sequence_demoobjectx",
                this,
                typeof(long));

            sequences[("sequence_demoobjectx", null)] = sequence_demoobjectx;

            var sequence_systemlog = new RuntimeSequence(
                "sequence_systemlog",
                this,
                typeof(long));

            sequences[("sequence_systemlog", null)] = sequence_systemlog;

            var sequence_tablepartition = new RuntimeSequence(
                "sequence_tablepartition",
                this,
                typeof(long));

            sequences[("sequence_tablepartition", null)] = sequence_tablepartition;

            AddAnnotation("Relational:Sequences", sequences);
            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "9.0.2");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
